
server.port= 8090

#datasource
spring.datasource.url=jdbc:mysql://31.97.63.120:3306/CARYANAMINDIA
spring.datasource.username=usermy
spring.datasource.password=Password@789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.main.allow-circular-references=true

spring.mail.username=ss
spring.mail.password=em

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
jwt.secret-key=A$93kLp@Jf!8kZnQwB#v7PxY&6Ru^2tG
spring.mail.properties.mail.smtp.auth=true

## For File Upload In Digital Ocean
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
do.CDN.No = https://carsimages.blr1.digitaloceanspaces.com

# Cloudflare R2 S3 Config
cloudflare.r2.account-id=f267f565da2ff555a00ecbf075f5acf0
cloudflare.r2.access-key=62db19c84ee36a48ebd6f451aa2a54e1
cloudflare.r2.secret-key=a00083f41a27e81b20751738950fda8d18791816aec622be54f18d8cdd31dd9e
cloudflare.r2.bucket=caryanamindia
cloudflare.r2.endpoint=https://f267f565da2ff555a00ecbf075f5acf0.r2.cloudflarestorage.com



# Socket.IO properties
socketio.host=0.0.0.0
#socketio.port=3000
socketio.port=8090
socketio.bossCount=1
socketio.workCount=100
socketio.allowCustomRequests=true
socketio.upgradeTimeout=10000
socketio.pingTimeout=60000
socketio.pingInterval=25000
socketio.maxFramePayloadLength=1048576
socketio.maxHttpContentLength=1048576


# JWT
app.jwt.secret=ReplaceThisWithAStrongSecretKey
app.jwt.expirationMs=3600000
